sudo: required
services:
    - docker

before_install:
    - docker build -t adeaver16/udemy-docker -f Dockerfile.dev .

# runs the tests
script:
    - docker run adeaver16/udemy-docker npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "udemy-docker"
    env: "UdemyDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-442293731715"
    bucket_path: "udemy-docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
